---
# This playbook runs sanity test on an existing Zowe instance

# ============================================================================
# validate variables
- import_role:
    name: common
    tasks_from: validate_variables
  vars:
    variable_list:
    - zowe_sanity_test_root_dir
    - zowe_root_dir
    - zowe_instance_dir
    - zos_zosmf_port
    - zowe_proclib_membername
    - zowe_job_prefix
    - zowe_zlux_port
    - zowe_apiml_gateway_port
    - zowe_jobs_api_port
    - zowe_mvs_api_port
    - zowe_sanity_test_testcases
